### ISSUE TITLE
Missing BNSF loop support

### ISSUE THREAD

**Issue by mrsobakin** [mrsobakin/cc2_audio_encoder#4]
A separate issue for the loop problem described in #2

**Comment by mrsobakin** [comment]
@LabMember12, I've added loop support. For now, it's in `bnsf_loop` [branch](https://github.com/mrsobakin/cc2_audio_encoder/tree/bnsf_loop). 

Also, I've changed some arguments for `cc2_audio_encoder`. You can read about loop and stereo arguments either in new `README.md`, or using `python3 -m cc2_audio_encoder bnsf -h` command. 

You can try it. If there's no issues, I'll push changes to the main branch.

**Comment by LabMember12** [comment]
Thank you very much! I'll write here right after check-up recent updates.

**Comment by LabMember12** [comment]
Hello, I tested. It gives me some error when I'm trying to add loop info.
![image](https://user-images.githubusercontent.com/115190459/226439203-030ffc3d-23e0-4060-a15a-6d3f0f343621.png)

**Comment by mrsobakin** [comment]
Oops, my bad. Try latest version, it should work now.

By the way, you can omit `--loop-start`, since the 0 is the default value.
You also can omit `--loop` if you have at least one of loop boundaries (`--loop-start`, `--loop-end`) specified.
And, if you just want to loop the entire `.wav` file, you can use `--loop` without specifying boundaries. It will automatically determine the last sample of the given audio file.

**Comment by LabMember12** [comment]
Thank you! Will test recent update then.

чт, 23 мар. 2023 г. в 00:01, Sobakin ***@***.***>:

**Comment by LabMember12** [comment]
Sorry for long delay. :C I checked for several times, it works perfectly with specific arguments. Thank you once again for priceless work.
